# Generated by Django 4.1.2 on 2022-12-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=40, null=True)),
                ('subject', models.CharField(choices=[('HINDI', 'Hindi'), ('ENGLISH', 'English'), ('MATH', 'Math'), ('BIO', 'Bio'), ('PHYSICS', 'Physics'), ('SOCIAL', 'Social'), ('NETWORKING', 'Networking'), ('C LANGUAGE', 'C Language'), ('PYTHON', 'Python'), ('MEDIA', 'Media'), ('SECURITY', 'Security'), ('JAVA', 'Java'), ('DATA ST', 'Data st'), ('DATA', 'data'), ('DBMS', 'DBMS'), ('AI', 'AI'), ('ACCOUNTS', 'Accounts'), ('BSC_subjects', 'Bsc Subjects'), ('MEDICAL_SUBJECTS', 'MEDICAL_SUBJECTS'), ('OTHERS Subjects', 'Others Subjects')], default=False, max_length=255)),
                ('max_no', models.IntegerField(null=True)),
                ('mark', models.IntegerField(null=True)),
                ('remark', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=40, null=True)),
                ('class_name', models.CharField(choices=[('LKG', 'LKG'), ('UKG', 'UKG'), ('ONE', 'One'), ('TWO', 'Two'), ('THREE', 'Three'), ('FOUR', 'Four'), ('FIVE', 'Five'), ('SIX', 'Six'), ('SEVEN', 'Seven'), ('EIGHT', 'Eight'), ('NINE', 'Nine'), ('TEN', 'Ten'), ('ELAVON', 'Elavon'), ('TWELVE', 'Twelve'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('BSC', 'Bsc'), ('BSC IT', 'Bsc IT'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('MEDICAL', 'Medical'), ('OTHERS', 'Others')], default=False, max_length=255)),
                ('roll_no', models.IntegerField(null=True)),
                ('gender', models.BooleanField(default=False)),
                ('mobile_no', models.IntegerField(null=True)),
            ],
        ),
    ]
