# Generated by Django 4.1.2 on 2022-12-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birthday',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
