# Generated by Django 4.1.2 on 2022-12-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_student_date_of_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], default=False, max_length=255),
        ),
    ]
