# Generated by Django 4.1.2 on 2022-12-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_remove_result_studentname_result_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
